using AgentRunner.Agents;

namespace AgentRunner.Tests.Mocks;

public class MockPlanAgent
{
    public static string GeneratePlan()
    {
        return @"# Plan
**Cycle:** 2026-02-22T12:00:00Z
**Generated by:** Plan Agent
**For:** Research Agent

---

## 1. Meta-Signals
- None identified this cycle.

## 2. Macro Market Conditions

| Dimension | Assessment |
| --------- | ---------- |
| Trend direction | Bullish |
| Sentiment | Risk-on |
| Volatility regime | Elevated |
| Liquidity conditions | Normal |
| Broader equity correlation | Tracking equities |
| Key macro factors | Fed meeting next week |

**Summary:** Market showing bullish momentum with elevated volatility ahead of Fed meeting.

## 3. Technical Signals

### BTC/USD

| Indicator | Timeframe | Observation | Signal strength |
| ---------- | --------- | ----------- | --------------- |
| RSI | 4H | Overbought at 72 | Medium |
| MACD | 1D | Bullish crossover | High |
| Volume | 1H | 1.5x average | Medium |

**Summary:** Strong bullish momentum but approaching overbought territory.

## 4. On-Chain Signals

| Event type | Asset | Detail | Signal strength |
| ---------- | ----- | ------ | --------------- |
| Exchange netflow | BTC | Net inflow of 2,500 BTC | Medium |

**Summary:** Some distribution visible but not significant.

## 5. News & Social Signals

### Crypto-Specific News
- **ETF inflows:** Bitcoin ETF saw $500M inflows yesterday.

### Social & Sentiment
- **@crypto_twitter:** Generally bullish sentiment.

## 6. Research Agenda

### Priority 1 — Investigate immediately
1. **Bitcoin ETF Flow Analysis**
   *Why:* Large ETF inflows suggest institutional interest.*Questions to answer:* What are the sustained flow trends?*Suggested sources:* Bloomberg, CoinShares

### Priority 2 — Investigate if time permits
2. **Fed Meeting Impact**
   *Why:* Upcoming Fed meeting could impact markets.*

## 7. Signals Deprioritized This Cycle
- None.
";
    }
}

public class MockResearchAgent
{
    public static string GenerateResearch()
    {
        return @"# Research
**Cycle:** 2026-02-22T12:00:00Z

---

## Executive Summary

Bitcoin ETF flows have been consistently positive over the past week, with $500M in daily inflows. The Fed meeting is likely to maintain rates, which could be bullish for crypto.

## Investigation Findings

### Bitcoin ETF Flow Analysis
- **Verdict:** Confirmed
- **Confidence:** High
- **Findings:**
  - $500M inflows on Feb 21
  - $350M inflows on Feb 20
  - Cumulative weekly: $2.1B
- **Sources:** CoinShares, Bloomberg
";
    }
}

public class MockAnalysisAgent
{
    public static string GenerateAnalysis()
    {
        return @"# Analysis
**Cycle:** 2026-02-22T12:00:00Z

---

## Market Overview

Strong bullish momentum with elevated volatility. Risk-on sentiment prevailing.

## Per-Asset Analysis

### BTC/USD
- **Direction:** Bullish
- **Conviction:** High
- **Key levels:** Support at $95,000, Resistance at $105,000
- **Invalidation:** Close below $90,000

### ETH/USD
- **Direction:** Bullish
- **Conviction:** Medium
- **Key levels:** Support at $3,200

## Current Position Assessment
- Current exposure: 60%
- Recommended action: Hold existing, consider 10% increase on pullback

## Risk Matrix
- Fed hawkish surprise: Medium likelihood, High impact
- ETF outflow reversal: Low likelihood, Medium impact
";
    }
}

public class MockSynthesisAgent
{
    public static string GenerateStrategy()
    {
        return @"{
  ""mode"": ""paper"",
  ""validUntil"": ""2026-02-23T12:00:00Z"",
  ""posture"": ""moderate"",
  ""rationale"": ""Bullish momentum with ETF flows, but elevated volatility suggests moderate stance"",
  ""risk"": {
    ""maxDrawdown"": 0.10,
    ""dailyLossLimit"": 0.03,
    ""maxExposure"": 0.70,
    ""maxPositionSize"": 0.15
  },
  ""positions"": [
    {
      ""asset"": ""BTC/USD"",
      ""direction"": ""long"",
      ""allocation"": 0.10,
      ""entryType"": ""market"",
      ""takeProfit"": [
        { ""target"": 105000, ""percentage"": 50 },
        { ""target"": 110000, ""percentage"": 50 }
      ],
      ""stopLoss"": 92000
    }
  ]
}";
    }
}
